version: '3.4'

services:
  webapi:
    image: aspapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
#      - .:/app
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    networks:
      - webapinetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webapinetwork

volumes:
  dbdata:

networks:
  webapinetwork:
    driver: bridge
